#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "Frame_Base.h"

//// end generated include

/** Implementing Frame */
class MainFrame : public Frame
{
protected:
	// Handlers for Frame events.
	void MainFrameOnLeftDown(wxMouseEvent &event);
	void MainFrameOnShow(wxShowEvent &event);

public:
	/** Constructor */
	MainFrame(wxWindow *parent);
	//// end generated class members
};

#endif // __MainFrame__
